
services:
  prisma-postgres:
    build: .
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: my-backend-app
    environment:
      - JWT_USER_PASS = process.env.JWT_USER_PASS ||'123123';
    ports: 
      - '3001:3001'
    depends_on:
      - prisma-postgres
    volumes:
      - .:/app

volumes:
  postgres-data:
   